### ISSUE TITLE
Loading kernel drivers?

### ISSUE THREAD

**Issue by DragonAC3221** [0x00Alchemist/Deadwing#1]
Hey, can we talk on Discord?
My discord sofiyablu

**Comment by 0x00Alchemist** [comment]
@DragonAC3221, Hi! If your questions are about the project itself, its problems, builds or about building your own functionality, it's better for me to write about it here. 

Otherwise, for contact: 0x00alchemist

**Comment by DragonAC3221** [comment]
do you think it is possible to load the driver into the system with your bootkit

**Comment by 0x00Alchemist** [comment]
> можно ли с помощью вашего проекта загрузить свой собственный драйвер .sys

No, the project wasn't designed for that. You don't need SMM driver to load your own drivers.

However, if there is still a need to load kernel drivers without creating a service (i.e., as it is done in my project) and there is a need for an SMM driver, you can solve this problem in the following way: modify the DXE driver from this project - add functionality for loading kernel drivers. 

DXE driver has a callback where you can fetch bootloader and kernel - [DeadwingBeforeExitBootServices](https://github.com/0x00Alchemist/Deadwing/blob/75df92068e9597c1d83d7b34601899b80e77aa3e/DeadwingDxe/DxeMain.c#L170). All you have to do is find `OsLoaderBlock` in the bootloader, find the kernel address in `OsLoaderBlock`, allocate a buffer for the driver and map driver. Also, if the kernel is patched, you need to translate some addresses, translation takes place in another callback - [DeadwingDxeGoneVirtual](https://github.com/0x00Alchemist/Deadwing/blob/75df92068e9597c1d83d7b34601899b80e77aa3e/DeadwingDxe/DxeMain.c#L126). Mapped drivers don't work with IOCTL initially (they don't have `DRIVER_OBJECT`), so we need to change the method for communication or call `IoCreateDriver` in the kernel driver to create `DRIVER_OBJECT`, then we can work with IOCTL.

I didn't plan to add such functionality as it can be quite unstable due to periodic changes in the kernel and bootloader.

**Comment by DragonAC3221** [comment]
thanks
